
language_dict = {
    'English': {
        'title': 'Weather Assistant',
        'city_menu': 'City',
        'remove_city_command': 'Remove City',
        'language_menu': 'Language',
        'english_command': 'English',
        'chinese_command': '中文',
        'help_menu': 'About',
        'update_failure': 'Update failed', 
        'success': 'Success',
        'city_added': 'City added',
        'city_removed': 'City removed',
        'city_not_found': 'City not found',
        'error': 'Error',
        'now_weather_title': 'Details',
        'now_weather_subtitle': ['Humidity', 'Feels Like', 'Wind Direction', 'Wind Scale', 'Pressure', 'Visibility', 'Cloud'],
        'now_weather_units': ['%', '°C', '', '', 'hPa', 'km', '%'],
        'air_quality_title': 'Air Quality',
        'air_quality_subtitle': ['AQI', 'Catagory', 'Primary Pollutant', 'PM10', 'PM2.5', 'NO2', 'SO2', 'CO', 'O3'],
        'air_quality_units': ['', '', '', 'μg/m³', 'μg/m³', 'μg/m³', 'μg/m³', 'mg/m³', 'μg/m³'],
        'wind_title': 'Wind',
        'wind_subtitle': ['Wind Direction', 'Wind Scale', 'Wind Speed', 'Degree'],
        'wind_direction': {'N': 'North', 'NE': 'Northeast', 'E': 'East', 'SE': 'Southeast', 'S': 'South', 'SW': 'Southwest', 'W': 'West', 'NW': 'Northwest', 'N/A': 'N/A'}, 
        'wind_units': ['', '', 'km/h', '°'],
        'sun_moon_title': 'Sun & Moon',
        'sun_moon_subtitle': ['Sunrise', 'Sunset', 'Moonrise', 'Moonset', 'Moon Phase'],
        'sun_moon_units': ['', '', '', '', ''],
        'no_warning': 'No warning',
        '24h_title': 'Temperature in 24 hours',
        '7d_title': 'Temperature in 7 days',
        'rain_title': 'Rain',
    },
    'Chinese': {
        'title': '天气助手',
        'city_menu': '城市',
        'remove_city_command': '删除城市',
        'language_menu': '语言',
        'english_command': 'English',
        'chinese_command': '中文',
        'help_menu': '关于',
        'update_failure': '更新失败',
        'success': '成功',
        'city_added': '城市已添加',
        'city_removed': '城市已删除',
        'city_not_found': '未找到城市',
        'error': '错误',
        'now_weather_title': '实时天气',
        'now_weather_subtitle': ['湿度', '体感温度', '风向', '风力等级', '气压', '能见度', '云量'],
        'now_weather_units': ['%', '°C', '', '', '百帕', '公里', '%'],
        'air_quality_title': '空气质量',
        'air_quality_subtitle': ['AQI', '级别', '首要污染物', 'PM10', 'PM2.5', 'NO2', 'SO2', 'CO', 'O3'],
        'air_quality_units': ['', '', '', 'μg/m³', 'μg/m³', 'μg/m³', 'μg/m³', 'mg/m³', 'μg/m³'],
        'wind_title': '风力风向',
        'wind_subtitle': ['风向', '风力等级', '风速', '风向角度'],
        'wind_direction': {'N': '北', 'NE': '东北', 'E': '东', 'SE': '东南', 'S': '南', 'SW': '西南', 'W': '西', 'NW': '西北', 'N/A': '无'},
        'wind_units': ['', '级', '公里/小时', '°'],
        'sun_moon_title': '日月信息',
        'sun_moon_subtitle': ['日出', '日落', '月出', '月落', '月相'],
        'sun_moon_units': ['', '', '', '', ''],
        'no_warning': '暂无预警',
        '24h_title': '24小时温度',
        '7d_title': '7天温度',
        'rain_title': '降雨情况',
    }
}    

language_alias_dict = {
    'English': 'en',
    'Chinese': 'zh',
}

language_idx_dict = {
    'English': 1,
    'Chinese': 2,
}
